### PR TITLE
Fixed complete packaging recycling disruptors list

### PR DESCRIPTION
**Pull request by DsposalTom**
@northernjamie I made a change to the documentation.

The historic complete packaging recycling disruptors list contained the 4 countries in the UK and not recycling disruptors.

I copied the list from [5_1_4 Component Catalogue](https://github.com/OpenDataManchester/PPP/blob/main/docs/5_Controlled_Lists/5_1_4_Component_Catalogue_Recycling_Disruptors.csv) I don't think it is "Perfect" but it is more correct than Wales, Scotland ...

### CODE REVIEW

**Comment by northernjamie** [comment]
It definitely is more perfect than it was, but there are still some things that look a bit odd, eg:

complete-packaging-disruptors-0013,Fillers that increase density PP above 0.97 g/cm2,
complete-packaging-disruptors-0014,Fillers that increase density of HDPE above 0.995 g/cm2

Can we do some gardening to remove the obvious ones? If indeed any are actually obvious?

**Comment by DsposalTom** [comment]
@northernjamie Yeah can do - on it now

**Comment by DsposalTom** [comment]
Ok @northernjamie I have gone through the list and done some rationalisation.

**Comment by northernjamie** [comment]
Great - that looks good to me now (though I can't comment on the detail). Happy for this to be merged.

**Pull request merged**
